name: Build extension

on:
  push:
    branches:
      - master

jobs:
  build_extension:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.0
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build the code
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: build
